import { Modal, PageMessage } from './Modal.jsx';
import {
  formatCurrency,
  formatDateTime,
  orderTypeLabels,
  paymentLabels,
} from '../utils/format.js';

export function OrderStatus({ status }) {
  return <span className={`order-status order-status--${status}`}>{status}</span>;
}

export function Receipt({ order }) {
  return (
    <article className="receipt" id="printable-receipt">
      <header className="receipt-brand">
        <span className="receipt-logo">L</span>
        <div><h2>Leslie&apos;s Restaurant</h2><p>Official order receipt</p></div>
      </header>

      <div className="receipt-meta">
        <div><span>Order number</span><strong>{order.order_number}</strong></div>
        <div><span>Date & time</span><strong>{formatDateTime(order.created_at)}</strong></div>
        <div><span>Order type</span><strong>{orderTypeLabels[order.order_type]}{order.table_number ? ` · Table ${order.table_number}` : ''}</strong></div>
        <div><span>Cashier</span><strong>{order.cashier_name}</strong></div>
      </div>

      <table className="receipt-items">
        <thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Amount</th></tr></thead>
        <tbody>
          {order.items.map((item) => (
            <tr key={item.id ?? item.menu_item_id}>
              <td><strong>{item.item_name}</strong>{item.notes && <small>Note: {item.notes}</small>}</td>
              <td>{item.quantity}</td>
              <td>{formatCurrency(item.unit_price_cents)}</td>
              <td>{formatCurrency(item.subtotal_cents)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <dl className="receipt-totals">
        <div><dt>Subtotal</dt><dd>{formatCurrency(order.subtotal_cents)}</dd></div>
        <div className="receipt-total"><dt>Total</dt><dd>{formatCurrency(order.total_cents)}</dd></div>
        <div><dt>Payment method</dt><dd>{paymentLabels[order.payment_method]}</dd></div>
        {order.payment_method === 'cash' && <>
          <div><dt>Cash received</dt><dd>{formatCurrency(order.amount_received_cents)}</dd></div>
          <div><dt>Change</dt><dd>{formatCurrency(order.change_cents)}</dd></div>
        </>}
      </dl>

      <footer className="receipt-footer">
        <p>Thank you for dining with us!</p>
        <small>This receipt was generated by Leslie&apos;s local restaurant system.</small>
      </footer>
    </article>
  );
}

export function ReceiptModal({ order, loading, error, onClose }) {
  return (
    <Modal title="Order receipt" subtitle="Review the saved transaction or print a customer copy." onClose={onClose}>
      <div className="receipt-modal-content">
        {loading && <div className="loading-state">Loading receipt…</div>}
        <PageMessage>{error}</PageMessage>
        {order && <Receipt order={order} />}
      </div>
      <div className="modal-actions receipt-actions">
        <button className="secondary-button" type="button" onClick={onClose}>Close</button>
        <button className="primary-button" type="button" onClick={() => window.print()} disabled={!order}>Print receipt</button>
      </div>
    </Modal>
  );
}
